<a href="https://colab.research.google.com/github/thinh2904/BT_Tong_Hop/blob/main/day5_RL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

In [24]:
V = np.zeros((3,4))

In [25]:
V[1,3]=-1
V[0,3] = 1
V[1,1] = -100
gamma = 0.9

In [26]:
V

array([[   0.,    0.,    0.,    1.],
       [   0., -100.,    0.,   -1.],
       [   0.,    0.,    0.,    0.]])

In [ ]:
V[0,2] = max( 0.8*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.8*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.8*(0 + gamma*V[1,2]))

In [ ]:
V

array([[   0.  ,    0.  ,    0.72,    1.  ],
       [   0.  , -100.  ,    0.  ,   -1.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ]])

In [ ]:
V[1,2] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.8*(0 + gamma*V[1,3]))

In [ ]:
V

array([[   0.    ,    0.    ,    0.72  ,    1.    ],
       [   0.    , -100.    ,    0.4284,   -1.    ],
       [   0.    ,    0.    ,    0.    ,    0.    ]])

In [ ]:
V[0,1] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.2*(0 + gamma*V[0,0]),
              0.2*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[0,0]))

In [ ]:
V

array([[   0.    ,    0.5184,    0.72  ,    1.    ],
       [   0.    , -100.    ,    0.4284,   -1.    ],
       [   0.    ,    0.    ,    0.    ,    0.    ]])

In [ ]:
V[0,2] = max( 0.8*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.8*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.8*(0 + gamma*V[1,2]))

In [ ]:
V[1,2] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.8*(0 + gamma*V[1,3]))

In [ ]:
V[0,1] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.2*(0 + gamma*V[0,0]),
              0.2*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[0,0]))

In [ ]:
V

array([[   0.        ,    0.57975264,    0.805212  ,    1.        ],
       [   0.        , -100.        ,    0.48975264,   -1.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ]])

In [27]:
def find_move(x,y, shape_v):
  up = (x-1, y)
  down = (x+1, y)
  left = (x, y-1)
  right = (x, y+1)

  list_move = [up, down, left, right]

  true_list_move = []
  for move in list_move:
    for stt,i in enumerate(move):
      if i < 0:
        break
      elif i >= shape_v[stt]:
        break
      if stt:
        true_list_move.append(move)
  return true_list_move

In [28]:
is_locks = [(1,1)]
results = []
for x in range(len(V)):
  for y in range(len(V[0])):
    list_move = find_move(x, y, (3, 4))
    for move in list_move:
        if move == is_locks[0]:
            list_move.remove(move)
    dict_move = {"cell": (x , y), "moves": list_move}
    results.append(dict_move)
for x in range(len(V)):
  for y in range(len(V[0])):
    list_move = find_move(x, y, V.shape)
    for move in list_move:
        if move == is_locks[0]:
            list_move.remove(move)
    dict_move = {"cell": (x , y), "moves": list_move}
    results.append(dict_move)

In [29]:
results

[{'cell': (0, 0), 'moves': [(1, 0), (0, 1)]},
 {'cell': (0, 1), 'moves': [(0, 0), (0, 2)]},
 {'cell': (0, 2), 'moves': [(1, 2), (0, 1), (0, 3)]},
 {'cell': (0, 3), 'moves': [(1, 3), (0, 2)]},
 {'cell': (1, 0), 'moves': [(0, 0), (2, 0)]},
 {'cell': (1, 1), 'moves': [(0, 1), (2, 1), (1, 0), (1, 2)]},
 {'cell': (1, 2), 'moves': [(0, 2), (2, 2), (1, 3)]},
 {'cell': (1, 3), 'moves': [(0, 3), (2, 3), (1, 2)]},
 {'cell': (2, 0), 'moves': [(1, 0), (2, 1)]},
 {'cell': (2, 1), 'moves': [(2, 0), (2, 2)]},
 {'cell': (2, 2), 'moves': [(1, 2), (2, 1), (2, 3)]},
 {'cell': (2, 3), 'moves': [(1, 3), (2, 2)]},
 {'cell': (0, 0), 'moves': [(1, 0), (0, 1)]},
 {'cell': (0, 1), 'moves': [(0, 0), (0, 2)]},
 {'cell': (0, 2), 'moves': [(1, 2), (0, 1), (0, 3)]},
 {'cell': (0, 3), 'moves': [(1, 3), (0, 2)]},
 {'cell': (1, 0), 'moves': [(0, 0), (2, 0)]},
 {'cell': (1, 1), 'moves': [(0, 1), (2, 1), (1, 0), (1, 2)]},
 {'cell': (1, 2), 'moves': [(0, 2), (2, 2), (1, 3)]},
 {'cell': (1, 3), 'moves': [(0, 3), (2, 3), (1

In [38]:
value_range = []
move_list = results[14]["moves"]
for i in range(len(move_list)):
    marked = move_list[i]
    sum = 0
    for j in move_list:
        if j == marked:
            sum += 0.8 * (0.0+gamma*V[marked])
        else:
            sum += 0.2/(len(move_list)-1)*(0.0+gamma*V[j])
    value_range.append(sum)

In [32]:
max(value_range)

0.7200000000000001

In [39]:
V[0,2] = max(value_range)

In [40]:
value_range = []
move_list = results[-6]["moves"]
for i in range(len(move_list)):
    marked = move_list[i]
    sum = 0
    for j in move_list:
        if j == marked:
            sum += 0.8 * (0.0+gamma*V[marked])
        else:
            sum += 0.2/(len(move_list)-1)*(0.0+gamma*V[j])
    value_range.append(sum)

In [41]:
max(value_range)

0.42840000000000006