<a href="https://colab.research.google.com/github/thinh2904/BT_Tong_Hop/blob/main/day5_RL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [21]:
# Ví dụ: Lấy tất cả các phần tử từ mảng 2 chiều arr
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_arr = [item for sublist in arr for item in sublist]
print(flattened_arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
V = np.zeros((3,4))

In [ ]:
V[1,3]=-1
V[0,3] = 1
V[1,1] = -100
gamma = 0.9

In [ ]:
V

array([[   0.,    0.,    0.,    1.],
       [   0., -100.,    0.,   -1.],
       [   0.,    0.,    0.,    0.]])

In [ ]:
V[0,2] = max( 0.8*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.8*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.8*(0 + gamma*V[1,2]))

In [ ]:
V

array([[   0.  ,    0.  ,    0.72,    1.  ],
       [   0.  , -100.  ,    0.  ,   -1.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ]])

In [ ]:
V[1,2] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.8*(0 + gamma*V[1,3]))

In [ ]:
V

array([[   0.    ,    0.    ,    0.72  ,    1.    ],
       [   0.    , -100.    ,    0.4284,   -1.    ],
       [   0.    ,    0.    ,    0.    ,    0.    ]])

In [ ]:
V[0,1] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.2*(0 + gamma*V[0,0]),
              0.2*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[0,0]))

In [ ]:
V

array([[   0.    ,    0.5184,    0.72  ,    1.    ],
       [   0.    , -100.    ,    0.4284,   -1.    ],
       [   0.    ,    0.    ,    0.    ,    0.    ]])

In [ ]:
V[0,2] = max( 0.8*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.8*(0 + gamma*V[0,1]) + 0.1*(0 + gamma*V[1,2]),
              0.1*(0.0 + gamma*V[0,3] ) + 0.1*(0 + gamma*V[0,1]) + 0.8*(0 + gamma*V[1,2]))

In [ ]:
V[1,2] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[2,2]) + 0.1*(0 + gamma*V[1,3]),
              0.1*(0.0 + gamma*V[0,2] ) + 0.1*(0 + gamma*V[2,2]) + 0.8*(0 + gamma*V[1,3]))

In [ ]:
V[0,1] = max( 0.8*(0.0 + gamma*V[0,2] ) + 0.2*(0 + gamma*V[0,0]),
              0.2*(0.0 + gamma*V[0,2] ) + 0.8*(0 + gamma*V[0,0]))

In [ ]:
V

array([[   0.        ,    0.57975264,    0.805212  ,    1.        ],
       [   0.        , -100.        ,    0.48975264,   -1.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ]])